# Firebase Service Configuration
project:
  id: ${FIREBASE_PROJECT_ID}
  region: ${GCLOUD_REGION}

firestore:
  rules: 'firestore.rules'
  indexes: 'firestore.indexes.json'

functions:
  runtime: nodejs22
  memory: 512MB
  timeout: 60s
  environment:
    NODE_ENV: ${NODE_ENV}
    VERTEX_AI_ENDPOINT: ${VERTEX_AI_ENDPOINT}

hosting:
  public: apps/web/dist
  rewrites:
    - source: '/api/**'
      function: api
    - source: '**'
      destination: '/index.html'
