config:
  dimensions: 768
  approximateNeighborsCount: 150
  distanceMeasureType: DOT_PRODUCT_DISTANCE
  algorithmConfig:
    treeAhConfig:
      leafNodeEmbeddingCount: 1000
      leafNodesToSearchPercent: 5
